name: Build and Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Setup Node.js
      uses: actions/setup-node@v4.0.1
      with:
        node-version: 'lts/*'

    - name: Install Dependencies
      run: |
        npm install -g pnpm
        pnpm install

    - name: Build
      run: pnpm run build

    - name: Deploy
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        pnpm run deploy -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
